# default false
release_mode = false
# default DEBUG, DEBUG INFO WARN ERROR OFF
log_level = "DEBUG"
# REDIS,MEMCACHED,IN_MEMORY(IN_MEMORY Default)
cache_store = "REDIS"

[app]
name = "tiniyoSip"
version = "0.0.1"

[server]
graceful = true
addr = ":9080"
# Domains
domain_api = "127.0.0.1"
domain_private_api = "localhost"

[redis]
server = "127.0.0.1:6379"
pwd = ""

[database]
name = "tiniyodb"
user_name = "tiniyo"
pwd  = "Tiniyo123"
host = "127.0.0.1"
port = "3306"
